---
- name: Set up EC2 instance for DevOps
  hosts: devops_servers
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Install Node.js (for React)
      apt:
        name: nodejs
        state: present

    - name: Install npm (for React)
      apt:
        name: npm
        state: present

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
        state: present

    - name: Install Python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install Ansible
      pip:
        name: ansible
        state: present
